name:                llvm-grader
version:             0.1.0.0
github:              "nuudlman/llvm-grader"
license:             BSD-3-Clause
author:              "Isaac Nudelman"
maintainer:          "isaac.nudelman@utexas.edu"
copyright:           "2025 Isaac Nudelman"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llvm-grader#readme>

dependencies:
- base >= 4.7 && < 5
- xml-conduit
- aeson
- path
- text
- vector
- unordered-containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Data.Gradescope

executables:
  llvm-grader-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-grader

tests:
  llvm-grader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llvm-grader
